name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v2
      - run: make say-hello
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 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                
